name: mytest
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test print secrets
        run: |
          mkdir secrets
          cd secrets
          echo "SECRET1 SECRET2 SECRET3" | tr ' ' '\n' >> list.txt

          file="list.txt"

          for line in $(cat $file); do 
            echo $line ${{ secrets[line] }}; 
          done
